Add support for nodenext moduleResolution
SamVerschueren/tsd pull request #149
Opened 2022-06-13 09:27 UTC by perrin4869

2022-06-13 10:08 UTC, perrin4869 commented
closes https://github.com/SamVerschueren/tsd/issues/144

2022-06-28 23:59 UTC, sindresorhus requested changes

2022-06-28 23:59 UTC, sindresorhus commented on readme.md
> +*Default options will apply if you don't override them explicitly.* You can't override the `moduleResolution` option. `moduleResolution` is set to `nodenext` if `module` is `nodenext`, `node16` if `m
It would be better to explain this using a code comment on line 139

2022-06-28 23:59 UTC, sindresorhus commented on source/test/fixtures/module-resolution/node16-from-package-json/index.js
> +module.exports.default = "foo";
Use single-quotes.

2022-06-28 23:59 UTC, sindresorhus commented on source/test/fixtures/module-resolution/node16-from-package-json/package.json
> +	"name": "foo",
I don't think it matters, but for correctness, this and the others, should have `"type": "module"`.

2022-06-28 23:59 UTC, sindresorhus commented on source/test/test.ts
> +test('use moduleResolution NodeNext when module is nodenext in tsconfig.json', async t => {
```suggestion
test('use moduleResolution `nodenext` when module is `nodenext` in tsconfig.json', async t => {
```

2022-06-30 22:27 UTC, merged